version: '3.8'

services:
  php-backend:
    image: basic-php-api
    container_name: php-backend
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=basic_database
      - DATABASE_USER=basic
      - DATABASE_PASSWORD=demoPass123!
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      - JWT_PASSPHRASE=MyJWTpass
    ports:
      - "9080:80"
    networks:
      - backend-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=MyRootPassword321!
      - MYSQL_DATABASE=basic_database
      - MYSQL_USER=basic
      - MYSQL_PASSWORD=demoPass123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
