api_platform:
    title: Basic API Products
    description: 'API documentation'
    version: '1.0.0'
    swagger:
        versions: [ 3 ]
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
